---
name: CI-Timer-App

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          docker build -t meka124/timerapp:${{env.SHORT_SHA}} .
      - name: Login to docker
        run: |
          echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
      - name: Push to Dockerhub
        run: |
          docker push meka124/timerapp:${{ env.SHORT_SHA }}
      - name: Configure git Author
        run: |
            git config --local user.email "ezemikey12@gmail.com"
            git config --local user.name "wesley-codes"
      - name: Update Helm Chart with new image tag
        run: |
            sed -i "s/tag:.*/tag: ${{env.SHORT_SHA}}/" ./timerapp/values.yaml
            git add ./timerapp/values.yaml
            git commit -m "Updated image tag to ${{env.SHORT_SHA}}"
            git push 


